version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.10.1
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      XPACK_MONITORING_ENABLED: false
      xpack.security.enabled: false
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      network.host: "0.0.0.0"

  kibana:
    image: kibana:8.10.1
    container_name: kibana
    restart: always
    volumes:
      - /c/Users/viuna-ict/elkProject/elkProject/elk/kibana/config:/opt/kibana/config
    ports:
      - "5622:5622"
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:8.10.1
    container_name: logstash
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - /c/Users/viuna-ict/elkProject/elkProject/elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "9600:9600"
    depends_on:
      - elasticsearch
